team_full_to_abbr= {
"Los Angeles Clippers": "lac",
"Cleveland Cavaliers": "cle"
}

exemplary_bets = [{'name': 'Bamba, Mo',
  'name_ESPN': 'MoBamba',
  'odds': 1.98,
  'line': 24.5,
  'bet_on_stat': 'ARP',
  'home': 'tor',
  'away': 'orl'},
 {'name': 'Suggs, Jalen',
  'name_ESPN': 'JalenSuggs',
  'odds': 1.83,
  'line': 20.5,
  'bet_on_stat': 'ARP',
  'home': 'tor',
  'away': 'orl'},
 {'name': 'Barnes, Scottie',
  'name_ESPN': 'ScottieBarnes',
  'odds': 1.89,
  'line': 24.5,
  'bet_on_stat': 'ARP',
  'home': 'tor',
  'away': 'orl'},
 {'name': 'VanVleet, Fred',
  'name_ESPN': 'FredVanVleet',
  'odds': 1.8,
  'line': 29.5,
  'bet_on_stat': 'ARP',
  'home': 'tor',
  'away': 'orl'},
 {'name': 'Trent Jr., Gary',
  'name_ESPN': 'GaryTrent Jr.',
  'odds': 1.89,
  'line': 20.5,
  'bet_on_stat': 'ARP',
  'home': 'tor',
  'away': 'orl'},
 {'name': 'Wagner, Franz',
  'name_ESPN': 'FranzWagner',
  'odds': 1.89,
  'line': 17.5,
  'bet_on_stat': 'ARP',
  'home': 'tor',
  'away': 'orl'},
 {'name': 'Carter Jr., Wendell',
  'name_ESPN': 'WendellCarter Jr.',
  'odds': 1.89,
  'line': 22.5,
  'bet_on_stat': 'ARP',
  'home': 'tor',
  'away': 'orl'},
 {'name': 'Anthony, Cole',
  'name_ESPN': 'ColeAnthony',
  'odds': 1.79,
  'line': 26.5,
  'bet_on_stat': 'ARP',
  'home': 'tor',
  'away': 'orl'},
 {'name': 'Anunoby, OG',
  'name_ESPN': 'OGAnunoby',
  'odds': 1.75,
  'line': 26.5,
  'bet_on_stat': 'ARP',
  'home': 'tor',
  'away': 'orl'},
 {'name': 'Achiuwa, Precious',
  'name_ESPN': 'PreciousAchiuwa',
  'odds': 1.89,
  'line': 21.5,
  'bet_on_stat': 'ARP',
  'home': 'tor',
  'away': 'orl'},
 {'name': 'Plumlee, Mason',
  'name_ESPN': 'MasonPlumlee',
  'odds': 1.8,
  'line': 22.5,
  'bet_on_stat': 'ARP',
  'home': 'mia',
  'away': 'cha'},
 {'name': 'Robinson, Duncan',
  'name_ESPN': 'DuncanRobinson',
  'odds': 1.89,
  'line': 17.5,
  'bet_on_stat': 'ARP',
  'home': 'mia',
  'away': 'cha'},
 {'name': 'Hayward, Gordon',
  'name_ESPN': 'GordonHayward',
  'odds': 1.89,
  'line': 26.5,
  'bet_on_stat': 'ARP',
  'home': 'mia',
  'away': 'cha'},
 {'name': 'Adebayo, Bam',
  'name_ESPN': 'BamAdebayo',
  'odds': 1.83,
  'line': 32.5,
  'bet_on_stat': 'ARP',
  'home': 'mia',
  'away': 'cha'},
 {'name': 'Bridges, Miles',
  'name_ESPN': 'MilesBridges',
  'odds': 1.95,
  'line': 28.5,
  'bet_on_stat': 'ARP',
  'home': 'mia',
  'away': 'cha'},
 {'name': 'Ball, LaMelo',
  'name_ESPN': 'LaMeloBall',
  'odds': 1.8,
  'line': 27.5,
  'bet_on_stat': 'ARP',
  'home': 'mia',
  'away': 'cha'},
 {'name': 'Lowry, Kyle',
  'name_ESPN': 'KyleLowry',
  'odds': 1.93,
  'line': 25.5,
  'bet_on_stat': 'ARP',
  'home': 'mia',
  'away': 'cha'},
 {'name': 'Butler, Jimmy',
  'name_ESPN': 'JimmyButler',
  'odds': 1.85,
  'line': 36.5,
  'bet_on_stat': 'ARP',
  'home': 'mia',
  'away': 'cha'},
 {'name': 'Sabonis, D.',
  'name_ESPN': 'D.Sabonis',
  'odds': 1.89,
  'line': 38.5,
  'bet_on_stat': 'ARP',
  'home': 'bkn',
  'away': 'ind'},
 {'name': 'Duarte, Chris',
  'name_ESPN': 'ChrisDuarte',
  'odds': 1.89,
  'line': 22.5,
  'bet_on_stat': 'ARP',
  'home': 'bkn',
  'away': 'ind'},
 {'name': 'Durant, Kevin',
  'name_ESPN': 'KevinDurant',
  'odds': 1.97,
  'line': 43.5,
  'bet_on_stat': 'ARP',
  'home': 'bkn',
  'away': 'ind'},
 {'name': 'Harden, James',
  'name_ESPN': 'JamesHarden',
  'odds': 1.8,
  'line': 36.5,
  'bet_on_stat': 'ARP',
  'home': 'bkn',
  'away': 'ind'},
 {'name': 'Turner, Myles',
  'name_ESPN': 'MylesTurner',
  'odds': 1.97,
  'line': 17.5,
  'bet_on_stat': 'ARP',
  'home': 'bkn',
  'away': 'ind'},
 {'name': 'Holmes, Richaun',
  'name_ESPN': 'RichaunHolmes',
  'odds': 1.93,
  'line': 24.5,
  'bet_on_stat': 'ARP',
  'home': 'no',
  'away': 'sac'},
 {'name': "Graham, Devonte'",
  'name_ESPN': "Devonte'Graham",
  'odds': 1.95,
  'line': 26.5,
  'bet_on_stat': 'ARP',
  'home': 'no',
  'away': 'sac'},
 {'name': 'Alexander-Walker, Nickeil',
  'name_ESPN': 'NickeilAlexander-Walker',
  'odds': 1.89,
  'line': 24.5,
  'bet_on_stat': 'ARP',
  'home': 'no',
  'away': 'sac'},
 {'name': 'Ingram, Brandon',
  'name_ESPN': 'BrandonIngram',
  'odds': 1.93,
  'line': 35.5,
  'bet_on_stat': 'ARP',
  'home': 'no',
  'away': 'sac'},
 {'name': "Fox, De'Aaron",
  'name_ESPN': "De'AaronFox",
  'odds': 1.89,
  'line': 34.5,
  'bet_on_stat': 'ARP',
  'home': 'no',
  'away': 'sac'},
 {'name': 'Barnes, Harrison',
  'name_ESPN': 'HarrisonBarnes',
  'odds': 1.93,
  'line': 27.5,
  'bet_on_stat': 'ARP',
  'home': 'no',
  'away': 'sac'},
 {'name': 'Haliburton, Tyrese',
  'name_ESPN': 'TyreseHaliburton',
  'odds': 2.05,
  'line': 21.5,
  'bet_on_stat': 'ARP',
  'home': 'no',
  'away': 'sac'},
 {'name': 'Valanciunas, Jonas',
  'name_ESPN': 'JonasValanciunas',
  'odds': 1.79,
  'line': 34.5,
  'bet_on_stat': 'ARP',
  'home': 'no',
  'away': 'sac'},
 {'name': 'Covington, Robert',
  'name_ESPN': 'RobertCovington',
  'odds': 1.99,
  'line': 13.5,
  'bet_on_stat': 'ARP',
  'home': 'por',
  'away': 'lac'},
 {'name': 'Zubac, Ivica',
  'name_ESPN': 'IvicaZubac',
  'odds': 1.99,
  'line': 18.5,
  'bet_on_stat': 'ARP',
  'home': 'por',
  'away': 'lac'},
 {'name': 'Bledsoe, Eric',
  'name_ESPN': 'EricBledsoe',
  'odds': 1.79,
  'line': 21.5,
  'bet_on_stat': 'ARP',
  'home': 'por',
  'away': 'lac'},
 {'name': 'Nurkic, Jusuf',
  'name_ESPN': 'JusufNurkic',
  'odds': 1.89,
  'line': 27.5,
  'bet_on_stat': 'ARP',
  'home': 'por',
  'away': 'lac'},
 {'name': 'Batum, Nicolas',
  'name_ESPN': 'NicolasBatum',
  'odds': 1.82,
  'line': 16.5,
  'bet_on_stat': 'ARP',
  'home': 'por',
  'away': 'lac'},
 {'name': 'Jackson, Reggie',
  'name_ESPN': 'ReggieJackson',
  'odds': 1.81,
  'line': 26.5,
  'bet_on_stat': 'ARP',
  'home': 'por',
  'away': 'lac'},
 {'name': 'McCollum, CJ',
  'name_ESPN': 'CJMcCollum',
  'odds': 1.99,
  'line': 31.5,
  'bet_on_stat': 'ARP',
  'home': 'por',
  'away': 'lac'},
 {'name': 'George, Paul',
  'name_ESPN': 'PaulGeorge',
  'odds': 1.83,
  'line': 41.5,
  'bet_on_stat': 'ARP',
  'home': 'por',
  'away': 'lac'},
 {'name': 'Lillard, Damian',
  'name_ESPN': 'DamianLillard',
  'odds': 1.89,
  'line': 39.5,
  'bet_on_stat': 'ARP',
  'home': 'por',
  'away': 'lac'},
 {'name': 'Hardaway Jr, Tim',
  'name_ESPN': 'TimHardaway Jr',
  'odds': 1.97,
  'line': 23.5,
  'bet_on_stat': 'ARP',
  'home': 'den',
  'away': 'dal'},
 {'name': 'Powell, Dwight',
  'name_ESPN': 'DwightPowell',
  'odds': 1.82,
  'line': 15.5,
  'bet_on_stat': 'ARP',
  'home': 'den',
  'away': 'dal'},
 {'name': 'Finney-Smith, Dorian',
  'name_ESPN': 'DorianFinney-Smith',
  'odds': 1.89,
  'line': 17.5,
  'bet_on_stat': 'ARP',
  'home': 'den',
  'away': 'dal'},
 {'name': 'Doncic, Luka',
  'name_ESPN': 'LukaDoncic',
  'odds': 1.89,
  'line': 44.5,
  'bet_on_stat': 'ARP',
  'home': 'den',
  'away': 'dal'},
 {'name': 'Sexton, Collin',
  'name_ESPN': 'CollinSexton',
  'odds': 1.8,
  'line': 28.5,
  'bet_on_stat': 'ARP',
  'home': 'lal',
  'away': 'cle'},
 {'name': 'Allen, Jarrett',
  'name_ESPN': 'JarrettAllen',
  'odds': 1.8,
  'line': 23.5,
  'bet_on_stat': 'ARP',
  'home': 'lal',
  'away': 'cle'},
 {'name': 'Garland, Darius',
  'name_ESPN': 'DariusGarland',
  'odds': 1.95,
  'line': 25.5,
  'bet_on_stat': 'ARP',
  'home': 'lal',
  'away': 'cle'},
 {'name': 'Mobley, Evan',
  'name_ESPN': 'EvanMobley',
  'odds': 1.98,
  'line': 23.5,
  'bet_on_stat': 'ARP',
  'home': 'lal',
  'away': 'cle'},
 {'name': 'Markkanen, Lauri',
  'name_ESPN': 'LauriMarkkanen',
  'odds': 1.98,
  'line': 20.5,
  'bet_on_stat': 'ARP',
  'home': 'lal',
  'away': 'cle'},
 {'name': 'Davis, Anthony',
  'name_ESPN': 'AnthonyDavis',
  'odds': 1.8,
  'line': 37.5,
  'bet_on_stat': 'ARP',
  'home': 'lal',
  'away': 'cle'},
 {'name': 'Bazemore, Kent',
  'name_ESPN': 'KentBazemore',
  'odds': 1.8,
  'line': 13.5,
  'bet_on_stat': 'ARP',
  'home': 'lal',
  'away': 'cle'}]

